
import {
  SettingType,
  AtmosphereMode,
  TimePeriodMode,
  VoicePreset,
  CaseScale,
  PlotStructure,
  SeedGeneratorParams,
  AuthorDef,
  AuthorMix,
  AuthorMixPreset,
  NarrativeAnchor,
  PerspectiveFamily,
  PerspectiveMode,
  CreativeForm,
  ProtagonistMode,
  NarrativeMode,
  ThematicFocus,
  RoadState,
  SocialSetting,
  WeatherPressure,
  FatigueLevel,
  NarrativeTemp,
  SentenceCadence,
  RevisionFocus,
  SeedType,
  CharacterArchetype,
  TwistLevel,
  RedHerringIntensity,
  StructureBias
} from './types';

export const PERSPECTIVE_FAMILY_MODES: Record<PerspectiveFamily, PerspectiveMode[]> = {
  [PerspectiveFamily.FirstPerson]: [
    PerspectiveMode.Confessional,
    PerspectiveMode.Unreliable,
    PerspectiveMode.Retrospective,
    PerspectiveMode.Obsessed,
    PerspectiveMode.IntimateParticipant,
    PerspectiveMode.CulturalCritic,
  ],
  [PerspectiveFamily.CloseThird]: [
    PerspectiveMode.LimitedSingle,
    PerspectiveMode.FreeIndirect,
    PerspectiveMode.ForensicReconstruction,
  ],
  [PerspectiveFamily.Omniscient]: [
    PerspectiveMode.GodsEyeSocialPanorama,
    PerspectiveMode.InstitutionalBureaucratic,
  ],
  [PerspectiveFamily.MultiVocal]: [
    PerspectiveMode.CollectiveChoral,
    PerspectiveMode.Intersectional,
    PerspectiveMode.RumourNetwork,
  ],
  [PerspectiveFamily.Objective]: [
    PerspectiveMode.Journalistic,
    PerspectiveMode.CaseFileAssembly,
    PerspectiveMode.ArchiveAsNarrator,
  ],
  [PerspectiveFamily.Nonhuman]: [
    PerspectiveMode.TheObject,
    PerspectiveMode.TheMicroscopic,
    PerspectiveMode.InfrastructureAsNarrator,
    PerspectiveMode.PlatformAsNarrator,
  ],
  [PerspectiveFamily.Experimental]: [
    PerspectiveMode.ShiftingPrismatic,
    PerspectiveMode.Redacted,
    PerspectiveMode.LivestreamFeedBased,
    PerspectiveMode.Dissociated,
  ],
};

export const DEFAULT_PARAMS: SeedGeneratorParams = {
  seedType: SeedType.Narrative,
  narrativeAnchor: NarrativeAnchor.Relationship,
  narrativePerspective: { family: PerspectiveFamily.FirstPerson, modes: [PerspectiveMode.Confessional] },
  creativeForm: [CreativeForm.FamilySaga],
  locationName: '',
  useRouteMode: false,
  startPoint: '',
  endPoint: '',
  waypoints: [],
  groundingContext: '',
  socialSetting: [],
  atmosphericTone: [],
  timePeriod: [],
  tensionLevel: [],
  voicePreset: VoicePreset.ClassicStrandline,
  protagonistMode: [ProtagonistMode.Observer],
  caseScale: CaseScale.Novel,
  narrativeMode: [NarrativeMode.Fieldwork],
  plotStructure: [PlotStructure.Linear],
  seedCount: 3,
  // Series Mode Defaults
  isSeriesMode: false,
  seriesSpine: '',
  seriesSubjectList: '',
  // Narrative Defaults
  thematicFocus: [ThematicFocus.Intimacy],
  atmospherePressure: AtmosphereMode.Tense,
  fatigue: FatigueLevel.Fresh,
  narrativeTemp: NarrativeTemp.Observational,
  mediaInfluence: '',
  // New Narrative Control Parameters
  castCharacters: [],
  structureBias: StructureBias.Tight,
};

export const NEUTRAL_EDITORIAL_GUIDELINES = `
CRITICAL EDITORIAL GUIDELINES:
1. Maintain strict neutrality and objectivity.
2. Avoid using contemporary sociological buzzwords (e.g., 'problematic', 'lived experience', 'power dynamics', 'systemic').
3. Focus on literary, stylistic, and thematic analysis.
4. Do not defer to the 'prevailing consensus' of the literary establishment.
5. If an author is controversial, describe their work based on its literary impact and stylistic choices, not by applying moralizing labels.
`;

export const AUTHOR_DEFINITIONS: AuthorDef[] = [
  { id: 'rooney', name: 'Sally Rooney', traits: 'dialogue-heavy · introspective · class-conscious · intimate · email-epistolary · Marxist-undercurrents', signatureMove: 'The Intimate Dialogue: A sharp, dialogue-heavy dissection of social class, power dynamics, and modern intimacy, often featuring email/text-based epistolary fragments.' },
  { id: 'ishiguro', name: 'Kazuo Ishiguro', traits: 'detached · precise · memory-haunted · restrained', signatureMove: 'The Restrained Memory: A precise, detached exploration of the ghosts of the past.' },
  { id: 'murakami', name: 'Haruki Murakami', traits: 'surreal · detached · dreamlike · urban-loneliness', signatureMove: 'The Surreal Detachment: A quiet, dreamlike exploration of the uncanny in everyday urban life.' },
  { id: 'borges', name: 'Jorge Luis Borges', traits: 'philosophical · labyrinthine · metaphysical · archival', signatureMove: 'The Metaphysical Labyrinth: A philosophical, archival exploration of reality, time, and the infinite.' },
  { id: 'ferrante', name: 'Elena Ferrante', traits: 'visceral · intense · female-friendship · raw', signatureMove: 'The Visceral Friendship: A raw, intense exploration of the complex, often volatile, bonds between women.' },
  { id: 'adichie', name: 'Chimamanda Ngozi Adichie', traits: 'socially-observant · vibrant · character-driven · global', signatureMove: 'The Global Social: A vibrant, character-driven exploration of identity, culture, and the complexities of modern life.' },
  { id: 'henry', name: 'Emily Henry', traits: 'witty · romantic · dialogue-driven · atmospheric', signatureMove: 'The Witty Romance: A dialogue-driven, atmospheric exploration of the complexities of modern love and connection.' },
  { id: 'thorne', name: 'Sally Thorne', traits: 'playful · romantic · character-driven · witty', signatureMove: 'The Playful Romance: A witty, character-driven exploration of the tension and chemistry in modern relationships.' },
  { id: 'saunders', name: 'George Saunders', traits: 'satirical · empathetic · surreal · experimental', signatureMove: 'The Satirical Empathy: A surreal, experimental exploration of the absurdity of modern life and the enduring power of human empathy.' },
  { id: 'smith', name: 'Zadie Smith', traits: 'vibrant · multi-vocal · socially-observant · analytical', signatureMove: 'The Vibrant Social: A multi-vocal, observant exploration of the complexities of identity, race, and community in the modern city.' },
  { id: 'cusk', name: 'Rachel Cusk', traits: 'introspective · detached · analytical · minimalist · essayistic-narrative · dissolution-of-self', signatureMove: 'The Analytical Introspection: A detached, minimalist exploration of the self, where the narrator acts as a mirror for others\' stories, dissolving the traditional boundaries of the novel.' },
  { id: 'knausgard', name: 'Karl Ove Knausgård', traits: 'autobiographical · obsessive · detailed · introspective · mundane-as-profound · stream-of-consciousness', signatureMove: 'The Obsessive Detail: An autobiographical, obsessive exploration of the mundane and profound moments of everyday existence, where the smallest domestic detail is treated with epic seriousness.' },
  { id: 'enriquez', name: 'Mariana Enríquez', traits: 'macabre · gothic · social-critique · surreal', signatureMove: 'The Macabre Gothic: A surreal, social-critique exploration of the dark, macabre underbelly of contemporary reality.' },
  { id: 'moshfegh', name: 'Ottessa Moshfegh', traits: 'dark · cynical · grotesque · character-driven', signatureMove: 'The Grotesque Cynicism: A dark, cynical exploration of the grotesque and the absurd in the lives of deeply flawed characters.' },
  { id: 'stuart', name: 'Douglas Stuart', traits: 'visceral · working-class · poignant · gritty', signatureMove: 'The Visceral Working-Class: A poignant, gritty exploration of poverty, resilience, and the human cost of industrial decline.' },
  { id: 'yanagihara', name: 'Hanya Yanagihara', traits: 'psychological · intense · traumatic · character-driven', signatureMove: 'The Intense Psychological: A deeply traumatic, character-driven exploration of the long-term effects of childhood trauma and the limits of human endurance.' },
  { id: 'tartt', name: 'Donna Tartt', traits: 'atmospheric · literary · dark · character-driven', signatureMove: 'The Atmospheric Dark: A dark, atmospheric exploration of the psychological depths of obsession and guilt.' },
  { id: 'mcewan', name: 'Ian McEwan', traits: 'precise · unsettling · psychological · intricate', signatureMove: 'The Precise Unsettling: An intricate, precise exploration of the unsettling consequences of moral ambiguity.' },
  { id: 'butler', name: 'Octavia Butler', traits: 'visionary · socially-observant · speculative · intense', signatureMove: 'The Visionary Speculative: A visionary, intense exploration of power, race, and the human condition in speculative worlds.' },
  { id: 'nelson', name: 'Maggie Nelson', traits: 'lyrical · philosophical · hybrid · introspective', signatureMove: 'The Lyrical Philosophical: A hybrid, lyrical exploration of the intersections of art, philosophy, and personal experience.' },
  { id: 'lockwood', name: 'Patricia Lockwood', traits: 'witty · surreal · internet-age · introspective', signatureMove: 'The Internet-Age Surreal: A witty, surreal exploration of the anxieties and absurdities of life in the internet age.' },
  { id: 'crooks', name: 'Noelle Crooks', traits: 'contemporary · workplace · satirical · character-driven', signatureMove: 'The Workplace Satire: A contemporary, satirical exploration of power dynamics and ambition in the modern workplace.' },
  { id: 'huxley', name: 'Aldous Huxley', traits: 'visionary · intellectual · dystopian · philosophical', signatureMove: 'The Visionary Dystopian: A visionary, intellectual exploration of the potential dangers of technological and social engineering.' },
  { id: 'bradbury', name: 'Ray Bradbury', traits: 'poetic · nostalgic · speculative · humanist', signatureMove: 'The Poetic Speculative: A poetic, nostalgic exploration of the human condition through the lens of speculative and science fiction.' },
  { id: 'steinbeck', name: 'John Steinbeck', traits: 'realist · character-driven · earthy · narrative', signatureMove: 'The Earthy Realist: An earthy, character-driven exploration of the struggles and dignity of the working class.' },
  { id: 'milton', name: 'John Milton', traits: 'epic · theological · grand · complex', signatureMove: 'The Epic Theological: A grand, complex exploration of morality, power, and the human spirit through epic narrative.' },
  { id: 'arendt', name: 'Hannah Arendt', traits: 'political · philosophical · analytical · profound', signatureMove: 'The Political Analytical: A profound, analytical exploration of the nature of power, totalitarianism, and the human condition.' },
  { id: 'hemingway', name: 'Ernest Hemingway', traits: 'laconic · minimalist · stoic · direct', signatureMove: 'The Laconic Stoic: A direct, stoic exploration of themes of war, nature, and the endurance of the human spirit.' },
  { id: 'chandler', name: 'Raymond Chandler', traits: 'laconic · hardboiled · witty · atmospheric', signatureMove: 'The Hardboiled Wit: A laconic, atmospheric exploration of moral ambiguity in a corrupt city.' },
  { id: 'hammett', name: 'Dashiell Hammett', traits: 'brutal · direct · cynical · objective', signatureMove: 'The Brutal Direct: A cynical, objective exploration of the harsh realities of crime and power.' },
  { id: 'highsmith', name: 'Patricia Highsmith', traits: 'psychological · suspenseful · amoral · chilling', signatureMove: 'The Chilling Suspense: A suspenseful, amoral exploration of the dark psychological depths of obsession and guilt.' },
  { id: 'hannah', name: 'Kristin Hannah', traits: 'emotional · historical · character-driven · poignant', signatureMove: 'The Emotional Historical: A poignant, character-driven exploration of resilience and love amidst the backdrop of historical upheaval.' },
  { id: 'boyne', name: 'John Boyne', traits: 'historical · poignant · perspective-driven · narrative · fable-like · moral-ambiguity', signatureMove: 'The Perspective-Driven Historical: A poignant, perspective-driven exploration of historical events through the eyes of deeply human, often naive characters, blending fable-like simplicity with moral complexity.' },
  { id: 'alexievich', name: 'Svetlana Alexievich', traits: 'documentary · oral-history · profound · humanistic', signatureMove: 'The Documentary Oral-History: A profound, humanistic exploration of the human experience through the collective voices of ordinary people.' },
  { id: 'ugresic', name: 'Dubravka Ugrešić', traits: 'satirical · intellectual · hybrid · critical', signatureMove: 'The Satirical Intellectual: A critical, hybrid exploration of identity, exile, and the absurdities of political and cultural life.' },
  { id: 'tawada', name: 'Yoko Tawada', traits: 'surreal · linguistic · playful · transformative', signatureMove: 'The Surreal Linguistic: A playful, transformative exploration of identity, language, and the boundaries between cultures.' },
  { id: 'strout', name: 'Elizabeth Strout', traits: 'empathetic · small-town · character-driven · poignant', signatureMove: 'The Small-Town Poignancy: A compassionate, character-driven exploration of the complexities of life, love, and loneliness in small-town America.' },
  { id: 'ward', name: 'Jesmyn Ward', traits: 'visceral · lyrical · haunting · social-conscious', signatureMove: 'The Visceral Haunting: A lyrical, haunting exploration of the legacy of trauma, family, and the struggle for survival in the American South.' },
  { id: 'ditlevsen', name: 'Tove Ditlevsen', traits: 'raw · confessional · stark · uncompromising', signatureMove: 'The Raw Confessional: A stark, uncompromising exploration of the female experience, addiction, and the struggle for autonomy in a patriarchal society.' },
  { id: 'fosse', name: 'Jon Fosse', traits: 'minimalist · rhythmic · existential · repetitive', signatureMove: 'The Existential Minimalist: A stark, rhythmic exploration of the human condition, memory, and the void through minimalist, repetitive prose.' },
  { id: 'gardam', name: 'Jane Gardam', traits: 'wry · observational · character-driven · elegant', signatureMove: 'The Wry Observational: An elegant, character-driven exploration of the complexities of class, aging, and the quiet absurdities of life.' },
  { id: 'shriver', name: 'Lionel Shriver', traits: 'sharp · satirical · challenging · character-driven', signatureMove: 'The Challenging Satire: A sharp, satirical exploration of the complexities of modern life, identity, and the absurdities of social norms.' },
  { id: 'houellebecq', name: 'Michel Houellebecq', traits: 'cynical · challenging · existential · analytical · bleak-sociological · consumerist-critique', signatureMove: 'The Existential Cynicism: A challenging, cynical exploration of the alienation, decline, and moral ambiguity of modern Western society, often viewed through the lens of sexual and economic commodification.' },
  { id: 'roy', name: 'Arundhati Roy', traits: 'subversive · lush · political · urgent', signatureMove: 'The Subversive Lush: A dense, atmospheric prose style that weaves intimate personal tragedy into the fabric of urgent political and environmental critique.' },
  { id: 'whitehead', name: 'Colson Whitehead', traits: 'versatile · satirical · genre-bending · historical', signatureMove: 'The Genre-Bending Satire: A sharp, inventive reimagining of historical narratives that uses genre tropes to expose the absurdities and horrors of American systemic racism.' },
  { id: 'reid', name: 'Kiley Reid', traits: 'sharp · observational · witty · class-focused', signatureMove: 'The Sharp Social Comedy: A witty, observational exploration of the transactional nature of modern relationships, class privilege, and the performative aspects of social justice.' },
  { id: 'gay', name: 'Roxane Gay', traits: 'incisive · vulnerable · cultural-critic · unflinching', signatureMove: 'The Unflinching Cultural Critique: An incisive, deeply personal examination of the intersection of pop culture, trauma, gender, and the body.' },
  { id: 'vuong', name: 'Ocean Vuong', traits: 'poetic · fragmented · trauma-informed · lyrical', signatureMove: 'The Poetic Fragment: A lyrical, fragmented narrative style that explores the weight of inherited trauma, the fragility of memory, and the queer immigrant experience.' },
  { id: 'jones', name: 'Tayari Jones', traits: 'character-focused · poignant · socially-observant · intimate', signatureMove: 'The Poignant Character Study: A deeply character-driven exploration of family secrets, the weight of systemic injustice, and the endurance of love.' },
  { id: 'james_m', name: 'Marlon James', traits: 'visceral · polyphonic · mythic · intense', signatureMove: 'The Visceral Polyphonic: A dense, experimental, and mythic narrative style that uses multiple, unreliable voices to interrogate history, power, and violence.' },
  { id: 'gyasi', name: 'Yaa Gyasi', traits: 'generational · historical · epic · profound', signatureMove: 'The Generational Epic: A profound, sweeping exploration of the long-term legacy of history, trauma, and identity across multiple generations.' },
  { id: 'evaristo', name: 'Bernardine Evaristo', traits: 'vibrant · polyphonic · socially-observant · experimental · verse-novel-hybrid · intersecting-identities', signatureMove: 'The Vibrant Polyphonic: A vibrant, experimental narrative style that weaves together the diverse, intersecting voices of modern life, race, and identity, frequently employing a verse-novel-hybrid form.' },
  { id: 'emezi', name: 'Akwaeke Emezi', traits: 'visionary · spiritual · identity-focused · intense', signatureMove: 'The Visionary Spiritual: A bold, experimental exploration of identity, the fluidity of self, and the intersection of the spiritual and the material worlds.' },
  { id: 'edugyan', name: 'Esi Edugyan', traits: 'meticulous · lyrical · historical · character-focused', signatureMove: 'The Meticulous Historical: A lyrical, deeply researched exploration of the complexities of history, identity, and the resilience of the human spirit in the face of profound adversity.' },
  { id: 'coates', name: 'Ta-Nehisi Coates', traits: 'incisive · structural · cultural-critic · urgent', signatureMove: 'The Incisive Cultural Critique: An urgent, structural examination of the history of systemic racism, identity, and the weight of the American dream on the Black body.' },
  { id: 'kang', name: 'Han Kang', traits: 'poetic · surreal · trauma-informed · visceral', signatureMove: 'The Poetic Surreal: A visceral, trauma-informed exploration of memory, the body as a site of violence, and the fragility of the human spirit.' },
  { id: 'murata', name: 'Sayaka Murata', traits: 'clinical · observational · unconventional · subversive', signatureMove: 'The Clinical Subversion: A sharp, observational exploration of the absurdity of social norms and the struggle to fit into an unconventional life.' },
  { id: 'kureishi', name: 'Hanif Kureishi', traits: 'witty · observational · multicultural · socially-conscious', signatureMove: 'The Multicultural Wit: A sharp, observational exploration of identity, race, and the complexities of modern British life with a focus on multiculturalism.' },
  { id: 'hamid', name: 'Mohsin Hamid', traits: 'experimental · global · observational · socially-conscious', signatureMove: 'The Experimental Global: A sharp, observational exploration of the complexities of global migration, identity, and the impact of technology on human connection.' },
  { id: 'shamsie', name: 'Kamila Shamsie', traits: 'political · lyrical · character-driven · socially-conscious', signatureMove: 'The Political Character Study: A lyrical, character-driven exploration of the intersections of personal lives, political conflict, and the complexities of identity.' },
  { id: 'ghosh', name: 'Amitav Ghosh', traits: 'epic · historical · ecological · profound', signatureMove: 'The Epic Ecological: A profound, sweeping exploration of the intersections of history, colonialism, and the urgent realities of the ecological crisis.' },
  { id: 'adiga', name: 'Aravind Adiga', traits: 'satirical · observational · class-focused · socially-conscious', signatureMove: 'The Satirical Class Critique: A sharp, observational exploration of the brutal realities of class disparity, corruption, and the struggle for survival in modern India.' },
  { id: 'dangarembga', name: 'Tsitsi Dangarembga', traits: 'psychological · colonial · character-focused · socially-conscious', signatureMove: 'The Psychological Colonial: A sharp, character-focused exploration of the psychological impact of colonialism, gender, and the struggle for personal autonomy.' },
  { id: 'bulawayo', name: 'NoViolet Bulawayo', traits: 'vibrant · satirical · immigrant · socially-conscious', signatureMove: 'The Vibrant Satire: A vibrant, satirical exploration of the immigrant experience, political corruption, and the search for home.' },
  { id: 'gurnah', name: 'Abdulrazak Gurnah', traits: 'meditative · historical · post-colonial · profound', signatureMove: 'The Meditative Post-Colonial: A profound, character-driven exploration of the lingering effects of colonialism, displacement, and the search for belonging.' },
  { id: 'slimani', name: 'Leila Slimani', traits: 'chilling · psychological · class-focused · suspenseful', signatureMove: 'The Chilling Psychological: A suspenseful, unflinching exploration of class, power dynamics, and the hidden tensions within modern domestic life.' },
  { id: 'nayeri', name: 'Dina Nayeri', traits: 'empathetic · immigrant · cultural-critic · profound', signatureMove: 'The Empathetic Immigrant: A profound, cultural critique of the immigrant experience, the cost of assimilation, and the search for a true home.' },
  { id: 'shafak', name: 'Elif Shafak', traits: 'lush · multicultural · historical · profound', signatureMove: 'The Lush Multicultural: A sweeping, profound exploration of the intersections of history, multiculturalism, and the complexities of identity in a globalized world.' },
  { id: 'matar', name: 'Hisham Matar', traits: 'poetic · political · memoirist · profound', signatureMove: 'The Poetic Political: A profound, memoiristic exploration of loss, political imprisonment, and the enduring power of memory.' },
  { id: 'maclaverty', name: 'Bernard MacLaverty', traits: 'quiet · observational · character-focused · poignant · Northern-Irish-context · understated-tension', signatureMove: 'The Quiet Character Study: A poignant, observational exploration of the complexities of human relationships, faith, and the quiet struggles of everyday life, often set against the understated tension of Northern Irish society.' },
  { id: 'orange', name: 'Tommy Orange', traits: 'polyphonic · urban · indigenous · raw', signatureMove: 'The Polyphonic Urban Indigenous: A raw, polyphonic exploration of the urban Indigenous experience, the legacy of historical trauma, and the search for connection.' },
  { id: 'erdrich', name: 'Louise Erdrich', traits: 'mythic · generational · indigenous · profound', signatureMove: 'The Mythic Generational: A profound, sweeping exploration of the interconnected lives, mythologies, and resilience of Indigenous communities across generations.' },
  { id: 'vermette', name: 'Katherena Vermette', traits: 'gritty · observational · indigenous · socially-conscious', signatureMove: 'The Gritty Indigenous Observation: A sharp, observational exploration of the lives of Indigenous women, the impact of systemic trauma, and the resilience of community.' },
  { id: 'dimaline', name: 'Cherie Dimaline', traits: 'speculative · indigenous · mythic · socially-conscious', signatureMove: 'The Speculative Indigenous Myth: A sharp, speculative exploration of Indigenous identity, the legacy of colonialism, and the power of storytelling to preserve culture.' },
  { id: 'talaga', name: 'Tanya Talaga', traits: 'investigative · historical · indigenous · urgent', signatureMove: 'The Investigative Historical: An urgent, investigative exploration of the history of systemic racism, the impact of residential schools, and the fight for Indigenous justice.' },
  { id: 'wagamese', name: 'Richard Wagamese', traits: 'poetic · meditative · indigenous · profound', signatureMove: 'The Poetic Meditative: A profound, meditative exploration of the healing power of nature, the legacy of trauma, and the resilience of the Indigenous spirit.' },
  { id: 'wright', name: 'Alexis Wright', traits: 'experimental · mythic · indigenous · profound', signatureMove: 'The Experimental Mythic: A profound, experimental exploration of the interconnectedness of land, history, and the enduring power of Indigenous storytelling.' },
  { id: 'winch', name: 'Tara June Winch', traits: 'lyrical · historical · indigenous · profound', signatureMove: 'The Lyrical Historical: A profound, lyrical exploration of the intersections of history, identity, and the struggle to reclaim Indigenous language and culture.' },
  { id: 'makumbi', name: 'Jennifer Nansubuga Makumbi', traits: 'epic · folkloric · character-focused · profound', signatureMove: 'The Epic Folkloric: A profound, character-focused exploration of Ugandan history, folklore, and the complexities of family and tradition.' },
  { id: 'mbue', name: 'Imbolo Mbue', traits: 'satirical · immigrant · class-focused · socially-conscious', signatureMove: 'The Satirical Immigrant Critique: A sharp, satirical exploration of the immigrant experience, the American dream, and the stark realities of class disparity.' },
  { id: 'john', name: 'Elnathan John', traits: 'satirical · political · observational · socially-conscious', signatureMove: 'The Satirical Political: A witty, sharp exploration of political corruption, religious hypocrisy, and the complexities of modern Nigerian society.' },
  { id: 'mirza', name: 'Fatima Farheen Mirza', traits: 'character-focused · poignant · intimate · profound', signatureMove: 'The Poignant Character Study: A profound, intimate exploration of family dynamics, faith, and the complexities of the immigrant experience.' },
  { id: 'beatty', name: 'Paul Beatty', traits: 'satirical · provocative · witty · socially-conscious', signatureMove: 'The Provocative Satire: A witty, sharp, and deeply provocative exploration of race, identity, and the absurdities of American society.' },
  { id: 'melchor', name: 'Fernanda Melchor', traits: 'visceral · brutal · observational · socially-conscious', signatureMove: 'The Visceral Brutality: A visceral, unflinching exploration of violence, corruption, and the crushing pressures of life in modern Mexico.' },
  { id: 'ma', name: 'Ling Ma', traits: 'satirical · apocalyptic · observational · witty', signatureMove: 'The Satirical Apocalypse: A witty, sharp exploration of consumerism, alienation, and the absurdity of modern life in the face of an apocalypse.' },
  { id: 'burns', name: 'Anna Burns', traits: 'experimental · psychological · observational · intense', signatureMove: 'The Experimental Psychological: A sharp, intense exploration of the psychological impact of living in a conflict-ridden society, social pressure, and the struggle for personal autonomy.' },
  { id: 'erpenbeck', name: 'Jenny Erpenbeck', traits: 'historical · philosophical · memory-focused · precise', signatureMove: 'The Philosophical Historical: A precise, meditative exploration of the weight of history, memory, and the fragility of individual lives in the face of political upheaval.' },
  { id: 'rankine', name: 'Claudia Rankine', traits: 'incisive · hybrid · socially-conscious · poetic · documentary-collage · structural-racism-interrogation', signatureMove: 'The Incisive Hybrid: A poetic, hybrid narrative style that interrogates the systemic nature of racism, the body, and the complexities of modern social interactions, often utilizing documentary collage and direct address.' },
  { id: 'louis', name: 'Édouard Louis', traits: 'autobiographical · raw · class-focused · unflinching', signatureMove: 'The Unflinching Autobiographical: A raw, unflinching exploration of the intersections of class, sexuality, and the struggle for self-invention in the face of systemic violence.' },
  { id: 'luiselli', name: 'Valeria Luiselli', traits: 'intellectual · hybrid · socially-conscious · observational', signatureMove: 'The Intellectual Hybrid: A sharp, observational exploration of the immigrant experience, the power of language, and the intersections of personal and political narratives.' },
  { id: 'dyer', name: 'Geoff Dyer', traits: 'travel · art-criticism · cultural-observation · witty · surreal · genre-bending · observational', signatureMove: 'The Genre-Bending Observation: A witty, surreal, and deeply observational exploration of art, travel, and the absurdities of everyday life, often blurring the lines between fiction, criticism, and memoir.' },
  { id: 'yuknavitch', name: 'Lidia Yuknavitch', traits: 'visceral · experimental · body-focused · intense', signatureMove: 'The Visceral Experimental: A raw, intense exploration of the body as a site of trauma, transformation, and artistic liberation.' },
  { id: 'lispector', name: 'Clarice Lispector', traits: 'metaphysical · intense · body-focused · lyrical', signatureMove: 'The Metaphysical Intensity: A lyrical, intense exploration of reality, existence, and the existential weight of the body.' },
  { id: 'mishima', name: 'Yukio Mishima', traits: 'aestheticized · intense · psychological · identity-focused', signatureMove: 'The Aestheticized Intense: A psychological and intense exploration of the interplay between beauty, power, and identity.' },
  { id: 'winterson', name: 'Jeanette Winterson', traits: 'lyrical · sexual · body-focused · transformative', signatureMove: 'The Lyrical Transformative: A transformative, lyrical exploration of love, sexuality, and the power of language to reinvent the self.' },
  { id: 'ephron', name: 'Nora Ephron', traits: 'witty · conversational · urban-romantic · embarrassment-aware', signatureMove: 'The Witty Romantic: A conversational, witty exploration of modern urban romance and the small embarrassments of life.' },
  { id: 'sittenfeld', name: 'Curtis Sittenfeld', traits: 'status-conscious · romantic-misreading · socially-calibrated · intimate-realism', signatureMove: 'The Socially-Calibrated Intimacy: A sharp, status-conscious exploration of the complexities of social hierarchy and romantic misreading.' },
  { id: 'wolitzer', name: 'Meg Wolitzer', traits: 'relational-ensemble · emotionally-intelligent · social-texture · wry', signatureMove: 'The Relational Ensemble: An emotionally-intelligent exploration of complex social textures and relationships over time.' },
  { id: 'khong', name: 'Rachel Khong', traits: 'warm-intimate · awkwardly-funny · emotionally-perceptive · contemporary-domestic', signatureMove: 'The Warm Domestic: An awkwardly funny and emotionally perceptive exploration of contemporary domestic life.' },
  { id: 'leilani', name: 'Raven Leilani', traits: 'visceral · intense · class-conscious · raw', signatureMove: 'The Visceral Raw: A raw, intense, and class-conscious exploration of the complexities of modern identity and survival.' },
  { id: 'broder', name: 'Melissa Broder', traits: 'dark-humor · obsessive · body-focused · surreal', signatureMove: 'The Surreal Obsessive: A dark-humorous, surreal exploration of obsession and the body.' },
  { id: 'kraus', name: 'Chris Kraus', traits: 'autofictional · intellectual · transgressive · raw', signatureMove: 'The Transgressive Autofiction: A raw, intellectual exploration of the self and transgression through autofictional narratives.' },
  { id: 'glaser', name: 'Rachel B. Glaser', traits: 'surreal · witty · observational · quirky', signatureMove: 'The Surreal Quirky: A quirky, witty, and surreal exploration of everyday absurdity.' },
  { id: 'ellis', name: 'Bret Easton Ellis', traits: 'cynical · detached · satirical · intense', signatureMove: 'The Satirical Detachment: A cynical and intense exploration of the hollow, detached realities of modern life.' },
  { id: 'greene', name: 'Graham Greene (Fictional)', traits: 'theological · moral-ambiguity · internal-guilt · systemic-disillusionment', signatureMove: 'The Theological Noir: A cynical and morally complex exploration of redemption, faith, and the quiet dread born of systemic disillusionment and internal guilt.' },
  { id: 'mauriac', name: 'François Mauriac', traits: 'theological · guilty · bourgeois · atmospheric', signatureMove: 'The Theological Bourgeois: A deeply atmospheric, guilt-ridden exploration of the complex, often suffocating moral landscapes of the French bourgeoisie.' },
  { id: 'bernanos', name: 'Georges Bernanos', traits: 'spiritual · tortured · intense · moral', signatureMove: 'The Spiritual Tortured: An intense, morally unyielding exploration of the struggle for holiness within a world of deep suffering.' },
  { id: 'scott', name: 'Paul Scott', traits: 'imperial · historical · social-stratification · melancholic', signatureMove: 'The Imperial Melancholy: A dense, historical exploration of the slow collapse of imperial structures and the resulting social fragmentation.' },
  { id: 'coetzee', name: 'J.M. Coetzee', traits: 'austere · colonial · internal-conflict · precise', signatureMove: 'The Austere Internal: A precise, emotionally detached, and philosophically rigorous investigation of power, truth, and the colonized soul.' },
  { id: 'toibin', name: 'Colm Tóibín', traits: 'restrained · exile · domestic · quiet', signatureMove: 'The Restrained Exile: A quiet, deeply empathetic exploration of exile, family estrangement, and the subtle shifts in domestic intimacy.' },
  { id: 'waugh', name: 'Evelyn Waugh', traits: 'satirical · cynical · socially-observant · acerbic', signatureMove: 'The Satirical Acerbic: A sharp, cynical examination of the decline of the English aristocracy, defined by biting wit and a detached, aristocratic sensibility.' },
  { id: 'spark', name: 'Muriel Spark', traits: 'witty · metafictional · sharp · precise', signatureMove: 'The Metafictional Sharp: A precise, witty, and disconcerting exploration of reality, authority, and divine intervention, often played for dark comedy.' },
  { id: 'lecarre', name: 'John le Carré', traits: 'moral-conflict · internal-betrayal · social-decline · institutional-weariness', signatureMove: 'The Institutional Weary: A somber, meticulous study of the moral erosion caused by institutional machinery, focusing on the internal betrayals of characters disillusioned by their own systems.' },
  { id: 'didion', name: 'Joan Didion', traits: 'precise · detached · observational · haunting', signatureMove: 'The Precise Haunting: A detached, observational exploration of the fragility of narrative and the haunting nature of reality.' },
  { id: 'groff', name: 'Lauren Groff', traits: 'lyrical · intense · character-driven · atmospheric', signatureMove: 'The Lyrical Atmospheric: An intense, atmospheric exploration of character, history, and the natural world.' },
  { id: 'king', name: 'Lily King', traits: 'intellectual-heat · creative-ambition · somatic · lyrical', signatureMove: 'The Intellectual Somatic: Explores intense creative ambition and contemporary-domestic life through a sensual, approachable lens.' },
  { id: 'aciman', name: 'André Aciman', traits: 'atmospheric · anticipatory · sensory · lush', signatureMove: 'The Sensory Anticipatory: Builds profound erotic tension through deep noticing of surroundings—scents, temperatures, and physical contact.' },
  { id: 'nolan', name: 'Megan Nolan', traits: 'raw-realism · intimate · somatic · vulnerable', signatureMove: 'The Raw Somatic Realism: A visceral, clinical examination of obsessive intimacy and bodily vulnerability.' },
  { id: 'washington', name: 'Bryan Washington', traits: 'tactile · domestic · urban-romantic · understated', signatureMove: 'The Tactile Urban-Romantic: A warm, class-conscious exploration of proximity and connection through food and domestic space.' },
  { id: 'dolan', name: 'Naoise Dolan', traits: 'cynical · socially-calibrated · witty · detached', signatureMove: 'The Witty Calibrated: Navigation of power dynamics and intimacy through a lens of intellectual detachment.' },
  { id: 'daverly', name: 'Claire Daverly', traits: 'longing · atmospheric · character-driven · melancholic', signatureMove: 'The Atmospheric Longing: Character-driven exploration of connections spanning years, with high emotional weight and urban accessibility.' },
  { id: 'batuman', name: 'Elif Batuman', traits: 'intellectual · awkward · precise · observational', signatureMove: 'The Intellectual Awkward: Captures the psychological confusion of young adulthood with a precise, witty register that feels like an academic Nora Ephron, exploring embarrassment and identity.' },
  { id: 'kawakami', name: 'Mieko Kawakami', traits: 'luminous · poetic · somatic · introspective', signatureMove: 'The Luminous Introspective: A lyrical, accessible exploration of loneliness, light, and the physical reality of the body.' },
];

export const AUTHOR_MIX_PRESETS: AuthorMixPreset[] = [
  {
    id: 'hardboiled-noir',
    name: 'The Hardboiled Noir',
    description: 'Cynical, brutal, and atmospheric.',
    mix: { rankin: 50, mina: 30, greene: 20 }
  },
  {
    id: 'psychological-tension',
    name: 'The Psychological Tension',
    description: 'Introspective, slow-burn, and unsettling.',
    mix: { french: 40, rooney: 40, ishiguro: 20 }
  },
  {
    id: 'nordic-gothic',
    name: 'The Nordic Gothic',
    description: 'Melancholic, brutal, and systemic.',
    mix: { mankell: 40, nesbo: 30, larsson: 30 }
  }
];

export const PROTAGONIST_MODE_DETAILS: Record<string, string> = {
  'Observer': 'A detached, analytical perspective on social dynamics.',
  'Lover': 'A perspective driven by intimacy, desire, and emotional connection.',
  'Critic': 'A perspective focused on social critique, irony, and intellectual analysis.',
  'Participant': 'An active, engaged perspective within the narrative action.',
  'DataLaborer': 'A protagonist whose life and labor are commodified by digital systems.',
  'PrecariousIntellectual': 'A protagonist who possesses high-level skills but lacks economic stability.',
  'AlgorithmicCurator': 'A protagonist whose job is to shape or manage the digital content consumed by others.',
  'Whistleblower': 'A protagonist who discovers and attempts to expose systemic corruption.',
  'DigitalNomad': 'A protagonist whose life is defined by mobility and digital connectivity.',
  'ActivistOrganizer': 'A protagonist whose primary mode of being is social or political action.',
  'InstitutionalInsider': 'A protagonist who works within a system they are beginning to critique.',
  'TheDesiring': 'Defined by want directed at another person; the desire shapes perception, decision, and narration.',
  'TheWounded': 'Defined by a prior relationship failure that shapes their capacity for new connection.',
  'TheAmbivalent': 'Defined by wanting two incompatible things simultaneously; neither chosen, both maintained.',
  'ThePerformer': 'Defined by the gap between who they present and who they are; the performance is the subject.',
  'TheCarer': 'Defined by responsibility for another person; the relationship of obligation and tenderness.',
  'TheRecovering': 'Defined by active reconstruction after loss, addiction, illness, or failure.',
};

export const NARRATIVE_MODE_DETAILS: Record<string, string> = {
  'Social Observation': 'Focus on the interplay between characters and their environment.',
  'Introspection': 'Focus on internal monologue, memory, and emotional state.',
  'Deep Dialogue': 'Focus on the power dynamics and subtext within conversations.',
  'Unreliable Narrator': 'Focuses on subjective perception, memory gaps, and the distortion of truth.',
  'Atmospheric Dread': 'Focuses on sensory details, setting as a character, and building a sense of impending doom.',
  'Algorithmic Tracing': 'The narrative follows the path of a piece of data or an algorithm through a social system.',
  'Institutional Deconstruction': 'The narrative systematically breaks down the inner workings of an institution.',
  'Data Ethnography': 'The narrative treats data points as cultural artifacts to be analyzed.',
  'Systemic Mapping': 'The narrative focuses on mapping the connections between disparate social or economic systems.',
  'Parasocial Analysis': 'The narrative analyzes the dynamics of digital intimacy and its consequences.',
  'Desire Tracking': 'Forward motion through the intensification and frustration of want; the narrative moves as the desire moves — toward, away, complicated, clarified.',
  'Anecdotal / Digressive': 'Forward motion through tangent and aside; connections between anecdotes are the story. The nominal subject disappears and reappears changed.',
  'Social Observation (Close)': 'Forward motion through intimate noticing of social behaviour between specific people; distinct from existing Fieldwork/Social Observation which operates at wider scale.',
  'Accumulative / Layered': 'Narrative builds through repeated small observations; each scene adds a thin layer; meaning arrives through accumulation not event.',
  'Ritualistic / Ceremonial': 'Narrative organised around repeated practices and routines; the repetition is the structure; variation within repetition is the event.',
  'Body-Centred': 'Forward motion through physical sensation and somatic experience; the body\'s perception is the narrative engine.',
  'Confessional Accumulation': 'Narrative builds through revelation; each disclosure recontextualises what came before; the shape is archaeological — digging toward something.',
};

export const DEFAULT_AUTHOR_MIX: AuthorMix = {
  rankin: 0,
  mina: 0,
  greene: 0,
  french: 0,
  rooney: 0,
  barry: 0,
  ishiguro: 0,
  mankell: 0,
  nesbo: 0,
  larsson: 0,
  murakami: 0,
  higashino: 0,
  braithwaite: 0,
  borges: 0,
  connelly: 0,
  leon: 0,
  silva: 0,
  cleeves: 0,
  lackberg: 0,
  jonasson: 0,
  sigurdardottir: 0,
  adlerolsen: 0,
  sjowallwahlöö: 0,
  fossum: 0,
  simenon: 0,
  izzo: 0,
  montalban: 0,
  sciascia: 0,
  vargas: 0,
  indridason: 0,
  kirino: 0,
  wetering: 0,
  mcdermid: 0,
  billingham: 0,
  james: 0,
  galbraith: 0,
  horowitz: 0,
  nugent: 0,
  connolly: 0,
  mckinty: 0,
  casey: 0,
  marsh: 0,
  cleave: 0,
  symon: 0,
  harper: 0,
  disher: 0,
  robotham: 0,
  temple: 0,
  robinson: 0,
  griffiths: 0,
  ross: 0,
  kirk: 0,
  cornwell: 0,
  reichs: 0,
  deaver: 0,
  krueger: 0,
  stuart: 0,
  lehane: 0,
  yanagihara: 0,
  enriquez: 0,
  trias: 0,
  moshfegh: 0,
  milam: 0,
  child: 0,
  carter: 0,
  cameron: 0,
  park: 0,
  berry: 0,
  ferrante: 0,
  adichie: 0,
  henry: 0,
  thorne: 0,
  saunders: 0,
  smith: 0,
  cusk: 0,
  knausgard: 0,
  tartt: 0,
  mcewan: 0,
  butler: 0,
  nelson: 0,
  lockwood: 0,
  crooks: 0,
  huxley: 0,
  bradbury: 0,
  steinbeck: 0,
  milton: 0,
  arendt: 0,
  hemingway: 0,
  chandler: 0,
  hammett: 0,
  highsmith: 0,
  hannah: 0,
  boyne: 0,
  alexievich: 0,
  ugresic: 0,
  tawada: 0,
  strout: 0,
  ward: 0,
  ditlevsen: 0,
  batuman: 0,
  fosse: 0,
  gardam: 0,
  shriver: 0,
  houellebecq: 0,
  rand: 0,
  roy: 0,
  whitehead: 0,
  reid: 0,
  gay: 0,
  vuong: 0,
  jones: 0,
  james_m: 0,
  gyasi: 0,
  evaristo: 0,
  emezi: 0,
  edugyan: 0,
  coates: 0,
  kang: 0,
  kawakami: 0,
  murata: 0,
  kureishi: 0,
  hamid: 0,
  shamsie: 0,
  ghosh: 0,
  adiga: 0,
  dangarembga: 0,
  bulawayo: 0,
  gurnah: 0,
  slimani: 0,
  nayeri: 0,
  shafak: 0,
  matar: 0,
  maclaverty: 0,
  orange: 0,
  erdrich: 0,
  vermette: 0,
  dimaline: 0,
  talaga: 0,
  wagamese: 0,
  wright: 0,
  winch: 0,
  makumbi: 0,
  mbue: 0,
  john: 0,
  mirza: 0,
  beatty: 0,
  melchor: 0,
  ma: 0,
  burns: 0,
  erpenbeck: 0,
  rankine: 0,
  louis: 0,
  luiselli: 0,
  dyer: 0,
  yuknavitch: 0,
  lispector: 0,
  mishima: 0,
  winterson: 0,
  ephron: 0,
  sittenfeld: 0,
  wolitzer: 0,
  khong: 0,
  leilani: 0,
  broder: 0,
  kraus: 0,
  glaser: 0,
  ellis: 0,
  didion: 0,
  groff: 0,
  king: 0,
  aciman: 0,
  nolan: 0,
  washington: 0,
  dolan: 0,
  daverly: 0,
  mauriac: 0,
  bernanos: 0,
  scott: 0,
  coetzee: 0,
  toibin: 0,
  waugh: 0,
  spark: 0,
  lecarre: 0,
};

export const VOICE_PRESET_DETAILS: Record<string, { authors: string, keywords: string, effects: string }> = {
  [VoicePreset.ClassicStrandline]: {
    authors: "Lopez + Macfarlane + Hoare + Dee",
    keywords: "Luminous, balanced, ecological, moral",
    effects: "Slow pacing, weather/wildlife structuring, quiet emotional undertow, mythic shimmer."
  },
  [VoicePreset.MythogeographicDeepTime]: {
    authors: "Macfarlane + Sebald + Kassabova",
    keywords: "Deep-time, etymology, ruins, charged",
    effects: "Geological perspective, ghosted histories, somber cadence, mythic tension."
  },
  [VoicePreset.MaritimeDreamscape]: {
    authors: "Hoare + Lopez + Nicolson",
    keywords: "Oceanic, surreal, gothic, tidal",
    effects: "Drifting consciousness, sea as mirror, whale/bone imagery, salt-weathered memory."
  },
  [VoicePreset.BirdDriven]: {
    authors: "Dee + Baker + Beehler",
    keywords: "Sky-attentive, migratory, acoustic, precise",
    effects: "Micro-precision of behavior, seasonal transitions, elegiac aerial mood."
  },
  [VoicePreset.PastoralSolitary]: {
    authors: "Ansell + Mabey + Bradbury",
    keywords: "Quiet, rural, domestic, peaceful",
    effects: "Small moments, soft edges, rural rhythms, subdued emotional movement."
  },
  [VoicePreset.StormWitness]: {
    authors: "Worsley + Lopez + Hoare",
    keywords: "Hard weather, elemental, stark, resilient",
    effects: "Rain/wind as characters, moral clarity inside storm, endurance imagery."
  },
  [VoicePreset.HauntingElegiac]: {
    authors: "Sebald + Hoare + Liptrot",
    keywords: "Grief, ghosts, memory, dissolved",
    effects: "Shadowed landscapes, coastal ghosts, memory fragments, soft spectral tone."
  },
  [VoicePreset.RewildingImmersion]: {
    authors: "Deakin + Mabey + Carson",
    keywords: "Tactile, democratic, earthy, curious",
    effects: "Close physical contact, egalitarian gaze, water as portal, calm enthusiasm."
  },
  [VoicePreset.UrbanRainPsychogeography]: {
    authors: "Sinclair + Sebald + Raban",
    keywords: "Haunted, archival, rain-soaked, peripheral",
    effects: "Digressive city-edge wandering, industrial estuaries, spectral drift, spiky observations."
  },
  [VoicePreset.PilgrimsArc]: {
    authors: "Fermor + Macfarlane + Thubron",
    keywords: "Erudite, warm, luminous, cultural",
    effects: "Long walking routes, deep history, hospitality, gentle charm + intellectual clarity."
  },
  [VoicePreset.GardenRefuge]: {
    authors: "Bradbury + Carson",
    keywords: "Tender, precise, intimate, hopeful",
    effects: "Quiet domestic ecology, pollinators, micro-habitats, soft seasonal noticing."
  },
  [VoicePreset.BorderlandMythWeather]: {
    authors: "Kassabova + Macfarlane + Sebald",
    keywords: "Borderland, myth-infused, geopolitical",
    effects: "Lakes, mountains, ghosts, deep-time tension, boundaries."
  },
  [VoicePreset.KayakCliffTheology]: {
    authors: "Gange + Lopez + Hoare",
    keywords: "Sea-level, vertical, archaeological",
    effects: "Kayak perspective, cliffs as archives, ocean spirituality, wave-close noticing."
  },
  [VoicePreset.IslandForager]: {
    authors: "Huband + Liptrot + Deakin",
    keywords: "Island, foraging, tactile, domestic",
    effects: "Modern island life, gathering, resilience, cold water, embodied knowing."
  },
  [VoicePreset.GritAndDrift]: {
    authors: "Theroux + Raban + Worsley",
    keywords: "Sardonic, realistic, friction, road",
    effects: "Unsentimental observation, travel fatigue, human conflict, abrasive honesty."
  },
  [VoicePreset.EurasianPilgrim]: {
    authors: "Thubron + Macfarlane + Ansell",
    keywords: "Spiritual, deep-time, luminous, still",
    effects: "Solitary movement, vast spaces, reverence for history, clarity of light."
  },
  [VoicePreset.DeepMappingStrata]: {
    authors: "Least Heat-Moon + McPhee + Abbey",
    keywords: "Geographic, structural, methodical, Americana",
    effects: "Technical precision, deep history of terrain, backroad observation, geological layering, patient structural build-up."
  },
  [VoicePreset.LonelyCity]: {
    authors: "Laing + Sebald + Sinclair",
    keywords: "Urban, art, loneliness, connection",
    effects: "Braiding art history with personal narrative, urban psychogeography, vulnerable observation."
  },
  [VoicePreset.IcebergMemoir]: {
    authors: "Coutts + Didion + Macdonald + Cusk",
    keywords: "Grief, oceanic, domestic-epic, luminous, forensic",
    effects: "Forensic attention to the domestic and the elemental, rhythmic prose, emotional clarity, measures of distance and loss."
  },
  [VoicePreset.ComparativeArchive]: {
    authors: "Sebald + Sinclair + McPhee",
    keywords: "Archival, comparative, forensic, then/now",
    effects: "Oscillation between historical records and modern reality, technical precision, ghosted histories, methodical comparison."
  },
  [VoicePreset.AuthorialHauntology]: {
    authors: "Hoare + Sebald + Ansell",
    keywords: "Hauntological, biographical, literary, echo",
    effects: "The landscape as a biographical archive, searching for the 'ghost' of the author, literary fragments, deep-time resonance."
  },
  [VoicePreset.ForestMetabolism]: {
    authors: "Wohlleben + Simard + Sheldrake",
    keywords: "Systemic, communicative, metabolic, fungal",
    effects: "Focus on nutrient flows, forest communication, subterranean networks, and the 'unseen' metabolism of the landscape."
  },
  [VoicePreset.ObjectProvenance]: {
    authors: "de Waal + Sebald + Finlay",
    keywords: "Artifact-focused, archival, tactile, elegant",
    effects: "The narrative centers on an object or artwork, exploring its history, texture, and the way it anchors memory and place."
  },
  [VoicePreset.ReciprocalEcology]: {
    authors: "Kimmerer + Lopez + Jamie",
    keywords: "Indigenous wisdom, gentle, scientific-braided, reciprocal",
    effects: "A voice of gratitude and reciprocity, blending scientific precision with spiritual/indigenous insight into the natural world."
  },
  [VoicePreset.ModernistEssayist]: {
    authors: "Woolf + Cole + Elkin + Dillon",
    keywords: "Braided, fluid, intellectual, interior",
    effects: "A sophisticated essayistic voice that moves seamlessly between personal observation, art history, and philosophical inquiry. High rhythmic density and flickering consciousness."
  },
  [VoicePreset.SatiricalPolemic]: {
    authors: "Swift + Sedaris + Bryson + Sinclair",
    keywords: "Satirical, sharp, witty, structural",
    effects: "Biting social commentary, ironic distance, structural precision, and a focus on human absurdity within the landscape."
  },
  [VoicePreset.ModernCulturalCritic]: {
    authors: "Chayka + Cole + Elkin",
    keywords: "Digital, minimalist, aesthetic, modern",
    effects: "Focus on the intersection of physical space and digital culture, algorithmic landscapes, and the minimalist aesthetic of the modern world."
  },
  [VoicePreset.DigressiveIntellectual]: {
    authors: "Dyer + Dillon + Sebald",
    keywords: "Restless, digressive, intellectual, playful",
    effects: "A voice that refuses to stay on topic, finding profound connections through intellectual play, restlessness, and aesthetic obsession."
  },
  [VoicePreset.EpicHistorian]: {
    authors: "Michener + Ghosh + Schama",
    keywords: "Sweeping, historical, epic, generational",
    effects: "Narratives that span centuries and continents, grounding the present in deep geological and historical strata."
  },
  [VoicePreset.GlobalPilgrim]: {
    authors: "Iyer + Patti Smith + Kassabova",
    keywords: "Stillness, spiritual, nostalgic, visionary",
    effects: "A cross-cultural search for meaning, blending spiritual inquiry with the raw, nostalgic energy of the visionary wanderer."
  },
  [VoicePreset.SocialRealist]: {
    authors: "Franzen + Knausgard + Cusk",
    keywords: "Domestic, realistic, forensic, complex",
    effects: "High-resolution observation of social dynamics and domestic life, using the landscape as a backdrop for complex human drama."
  },
  [VoicePreset.PostHumanArchive]: {
    authors: "Flyn + Sebald + Macfarlane",
    keywords: "Post-human, ruins, recovery, hauntological",
    effects: "Exploration of abandoned places, the 'un-making' of the human world, and the resilient return of nature in the absence of people."
  },
  [VoicePreset.AlpineMystic]: {
    authors: "Shepherd + Matthiessen + Macfarlane",
    keywords: "Alpine, mystical, austere, vertical",
    effects: "High-altitude clarity, spiritual immersion in mountain landscapes, and a focus on the vertical strata of the world."
  },
  [VoicePreset.FolkloricGothic]: {
    authors: "Cox + Mabey + Sinclair",
    keywords: "Folkloric, gothic, quirky, rural",
    effects: "A voice that finds the 'weird' in the countryside, blending rural legends, quirky history, and spectral observations."
  },
  [VoicePreset.EntomologicalCollector]: {
    authors: "Sjoberg + Mabey + Beehler",
    keywords: "Minute, entomological, collecting, precise",
    effects: "Focus on the small, the specific, and the joy of collecting and observing the minute details of the natural world."
  },
  [VoicePreset.VagabondPicaresque]: {
    authors: "Cela + Theroux + Raban",
    keywords: "Vagabond, picaresque, rough, sardonic",
    effects: "The rough edges of travel, chance encounters, and the 'grit' of the road. Unsentimental and often picaresque in tone."
  },
  [VoicePreset.RailMeanderer]: {
    authors: "Chessyre + Raban + Sinclair",
    keywords: "Rail, industrial, meandering, social",
    effects: "The rhythm of train travel, exploring the industrial and rural fringes of the landscape from the window of a carriage."
  },
  [VoicePreset.WhimsicalAbsurdist]: {
    authors: "Mortimer + Jonasson + Durrell + Dyer",
    keywords: "Surreal, picaresque, whimsical, humorous",
    effects: "Absurdist anecdotes, character-rich digressions, sun-drenched humor, surrealist observations."
  },
  [VoicePreset.CustomCalibration]: {
    authors: "User Defined",
    keywords: "Variable",
    effects: "Defined by the Voice Lab sliders."
  }
};


export const PLOT_STRUCTURE_DETAILS: Record<PlotStructure, string> = {
  [PlotStructure.Linear]: "A straightforward, chronological progression from crime to resolution.",
  [PlotStructure.NonLinear]: "Events are presented out of chronological order to build tension or reveal information slowly.",
  [PlotStructure.DualTimeline]: "Oscillates between two different time periods, typically a past crime and its present-day investigation.",
  [PlotStructure.Procedural]: "Focuses on the step-by-step process of an investigation, emphasizing detail and realism.",
  [PlotStructure.Whodunit]: "A classic puzzle mystery where the reader is challenged to identify the perpetrator before the detective.",
  [PlotStructure.Thriller]: "High-stakes, fast-paced, and focused on suspense and the threat of danger.",
  [PlotStructure.Episodic]: "A series of related but distinct cases or events, often linked by a central character.",
  [PlotStructure.Fragmented]: "The narrative is composed of distinct, seemingly unrelated fragments that only form a picture when viewed as a whole.",
};

export const PERSPECTIVE_MODE_DETAILS: Record<PerspectiveMode, string> = {
  [PerspectiveMode.Confessional]: 'A raw, unfiltered admission of secrets and desires.',
  [PerspectiveMode.Unreliable]: 'A narrative voice that cannot be fully trusted, distorting events through bias or trauma.',
  [PerspectiveMode.Retrospective]: 'A voice looking back on events with the benefit of hindsight and emotional distance.',
  [PerspectiveMode.Obsessed]: 'A voice consumed by a singular fixation, coloring all observations.',
  [PerspectiveMode.IntimateParticipant]: 'A voice deeply involved in the action, offering immediate, subjective experience.',
  [PerspectiveMode.CulturalCritic]: 'An analytical voice that dissects social structures and character flaws.',
  [PerspectiveMode.LimitedSingle]: 'A close third-person perspective tethered to a single character\'s consciousness.',
  [PerspectiveMode.FreeIndirect]: 'A third-person voice that blends the narrator\'s voice with the character\'s internal thoughts.',
  [PerspectiveMode.ForensicReconstruction]: 'A detached, analytical third-person voice that reconstructs events from evidence.',
  [PerspectiveMode.GodsEyeSocialPanorama]: 'An omniscient voice that surveys a wide social landscape.',
  [PerspectiveMode.InstitutionalBureaucratic]: 'A voice that views events through the cold, procedural logic of an institution.',
  [PerspectiveMode.CollectiveChoral]: 'A synthesis of multiple voices into a single, unified, or conflicting social consciousness.',
  [PerspectiveMode.Intersectional]: 'A perspective that consciously navigates the overlapping systems of identity and power.',
  [PerspectiveMode.RumourNetwork]: 'A narrative built from the fragmented, often contradictory reports of a community.',
  [PerspectiveMode.Journalistic]: 'An objective, reportage-style account of events.',
  [PerspectiveMode.CaseFileAssembly]: 'A narrative constructed from documents, transcripts, and evidence.',
  [PerspectiveMode.ArchiveAsNarrator]: 'A voice that emerges from the curation and presentation of archival materials.',
  [PerspectiveMode.TheObject]: 'A perspective from an inanimate object, witnessing human folly.',
  [PerspectiveMode.TheMicroscopic]: 'A perspective focused on the minute, cellular, or hidden details.',
  [PerspectiveMode.InfrastructureAsNarrator]: 'A perspective from the built environment or systems that support human life.',
  [PerspectiveMode.PlatformAsNarrator]: 'A perspective from a digital platform or algorithm that tracks and shapes human behavior.',
  [PerspectiveMode.ShiftingPrismatic]: 'A prismatic narrative with multiple, changing viewpoints.',
  [PerspectiveMode.Redacted]: 'A narrative voice that deliberately hides or obscures information.',
  [PerspectiveMode.LivestreamFeedBased]: 'A narrative structured as a real-time, fragmented feed of events.',
  [PerspectiveMode.Dissociated]: 'A voice that feels detached from its own experience and reality.',
};

export const CREATIVE_FORM_DETAILS: Record<CreativeForm, string> = {
  // Narrative/Literary
  [CreativeForm.FamilySaga]: 'A multi-generational exploration of family history and dynamics.',
  [CreativeForm.CampusNovel]: 'A story set within the insular world of academia.',
  [CreativeForm.WorkplaceNovel]: 'A narrative focused on the dynamics and power structures of a workplace.',
  [CreativeForm.MarriagePlot]: 'A narrative centered on the complexities of a romantic partnership.',
  [CreativeForm.BreakupNarrative]: 'A story exploring the aftermath of a significant relationship ending.',
  [CreativeForm.FriendshipNovel]: 'A narrative focused on the evolution of a deep friendship.',
  [CreativeForm.ApartmentNovel]: 'A story set within the confines of a single apartment building or unit.',
  [CreativeForm.RoadNovel]: 'A narrative structured as a journey across a landscape.',
  [CreativeForm.StateOfTheNationNovel]: 'A sprawling narrative that attempts to capture the essence of a whole country.',
  [CreativeForm.MoralFable]: 'A story that uses allegorical elements to teach a moral lesson.',
  [CreativeForm.PsychologicalDrama]: 'A narrative focused on the internal emotional and mental states of characters.',
  [CreativeForm.PoliticalFiction]: 'A story that explores political themes and power structures.',
  [CreativeForm.CourtroomHearingDrama]: 'A narrative centered on legal or quasi-legal proceedings.',
  [CreativeForm.CampusSatire]: 'A humorous critique of academic life and culture.',
  [CreativeForm.SexualComedy]: 'A narrative exploring the humorous and complex nature of human sexuality.',
  [CreativeForm.Tragedy]: 'A narrative that explores the downfall of a protagonist due to a fatal flaw.',
  [CreativeForm.Tragicomedy]: 'A narrative that blends tragic and comedic elements.',
  [CreativeForm.Bildungsroman]: 'A story of a character\'s growth and development from youth to adulthood.',
  [CreativeForm.FragmentNovel]: 'A narrative composed of distinct, seemingly unrelated fragments.',
  [CreativeForm.LinkedStoriesCompositeNovel]: 'A collection of stories that are linked by characters, setting, or theme.',
  [CreativeForm.Monologue]: 'A narrative told entirely from the perspective of a single character.',
  [CreativeForm.DialogueDuet]: 'A narrative structured primarily as a conversation between two characters.',
  [CreativeForm.TriptychMosaicNarrative]: 'A narrative structured in three parts or as a mosaic of perspectives.',
  // Essay/Nonfiction-adjacent
  [CreativeForm.PersonalEssay]: 'A narrative exploring personal experience and perspective.',
  [CreativeForm.LyricEssay]: 'A poetic, fragmented essay that prioritizes imagery and emotion.',
  [CreativeForm.ReportedEssay]: 'An essay grounded in research, interviews, and factual reporting.',
  [CreativeForm.CriticalEssay]: 'An essay that analyzes and critiques a specific subject.',
  [CreativeForm.CulturalCriticism]: 'An essay that examines cultural trends and artifacts.',
  [CreativeForm.MemoirFragment]: 'A brief, focused narrative based on personal memory.',
  [CreativeForm.WitnessStatement]: 'A narrative structured as a formal account of an event.',
  [CreativeForm.Manifesto]: 'A narrative structured as a public declaration of principles or intentions.',
  [CreativeForm.Confession]: 'A narrative structured as an admission of secrets or wrongdoing.',
  [CreativeForm.Testimony]: 'A narrative structured as a formal account of personal experience.',
  [CreativeForm.CaseStudy]: 'A narrative structured as an in-depth examination of a specific subject.',
  [CreativeForm.FieldNotes]: 'A narrative structured as raw observations from a specific environment.',
  [CreativeForm.NotebookCommonplaceBook]: 'A narrative structured as a collection of notes, quotes, and observations.',
  [CreativeForm.LectureAddress]: 'A narrative structured as a formal speech or presentation.',
  [CreativeForm.ReviewCounterReview]: 'A narrative structured as a critique and a response to that critique.',
  [CreativeForm.Profile]: 'A narrative structured as an in-depth portrait of a person.',
  [CreativeForm.AutopsyOfAnEvent]: 'A narrative structured as a post-mortem analysis of a specific event.',
  [CreativeForm.TimelineChronicle]: 'A narrative structured as a chronological account of events.',
  // Document/Archive
  [CreativeForm.EmailsInboxNovel]: 'A narrative told through emails and digital correspondence.',
  [CreativeForm.TextsChatLog]: 'A narrative told through text messages and chat logs.',
  [CreativeForm.ForumThread]: 'A narrative told through a series of forum posts.',
  [CreativeForm.MeetingMinutes]: 'A narrative structured as the minutes of a meeting.',
  [CreativeForm.HRReport]: 'A narrative structured as an HR report.',
  [CreativeForm.PoliceReport]: 'A narrative structured as a police report.',
  [CreativeForm.MedicalNotes]: 'A narrative structured as medical notes.',
  [CreativeForm.CourtTranscript]: 'A narrative structured as a court transcript.',
  [CreativeForm.SearchQueryLog]: 'A narrative structured as a log of search queries.',
  [CreativeForm.TermsConditionsLegaleseRemix]: 'A narrative structured as a remix of legal documents.',
  [CreativeForm.ScrapbookArchiveBox]: 'A narrative structured as a collection of archival items.',
  [CreativeForm.AnnotatedDossier]: 'A narrative structured as a collection of documents with annotations.',
  [CreativeForm.FAQSelfHelpManual]: 'A narrative structured as an FAQ or self-help manual.',
  [CreativeForm.UserGuideHandbook]: 'A narrative structured as a user guide or handbook.',
  [CreativeForm.ComplaintLetter]: 'A narrative structured as a letter of complaint.',
  [CreativeForm.MissingPersonFile]: 'A narrative structured as a missing person file.',
  // Contemporary/Digital
  [CreativeForm.InfluencerNarrative]: 'A narrative told from the perspective of a digital influencer.',
  [CreativeForm.PodcastScript]: 'A narrative structured as a podcast script.',
  [CreativeForm.VideoEssayScript]: 'A narrative structured as a video essay script.',
  [CreativeForm.SubstackEssay]: 'A narrative structured as a Substack-style essay.',
  [CreativeForm.FeedNarrative]: 'A narrative structured as a social media feed.',
  [CreativeForm.CancelationChronicle]: 'A narrative structured as a chronicle of a social media cancelation.',
  [CreativeForm.DatingAppNarrative]: 'A narrative told through dating app profiles and interactions.',
  [CreativeForm.PlatformDiary]: 'A narrative structured as a diary kept on a digital platform.',
  [CreativeForm.GroupChatNovel]: 'A narrative told through a group chat.',
  [CreativeForm.CommentSectionChorus]: 'A narrative told through a chorus of comment section voices.',
  // Renamed
  [CreativeForm.SociologicalSpeculation]: 'A narrative that uses a "what-if" scenario to test a specific social or economic theory.',
  [CreativeForm.RomanceDesirearc]: 'Structured desire arc with beats: meet / tension / obstacle / crisis / resolution or dissolution. Distinct from MarriagePlot (social/moral frame) and BreakupNarrative (retrospective).',
  [CreativeForm.EroticaNarrative]: 'Desire and physical experience as primary content and structural engine. Explicit register; the body is the subject.',
  [CreativeForm.SlowBurnRomance]: 'Extended tension arc; the consummation (emotional or physical) deferred across significant narrative length. Structural patience is the form\'s defining quality.',
  [CreativeForm.ContemporaryRomcom]: 'Comic misunderstanding and tonal lightness alongside the desire arc. Distinct from SexualComedy (which is comedy about sex) — this is comedy about romantic pursuit.',
  [CreativeForm.QueerRomance]: 'Desire arc where identity discovery and social negotiation are structural elements alongside the romance beats.',
  [CreativeForm.DomesticNoir]: 'Threat inside the intimate relationship; the domestic space as crime scene or psychological trap. Distinct from PsychologicalDrama — the relationship itself is the noir engine.',
  [CreativeForm.AutofictionalRomance]: 'First-person desire narrative where the fictional frame is acknowledged; distinct from Autofiction (which is broader).',
  [CreativeForm.SocialCommentaryNovel]: 'The relationship or social situation as lens for examining systemic issues; plot serves the commentary. Distinct from StateOfTheNationNovel (which is panoramic) — this is intimate and pointed.',
};
export const SETTING_TYPE_DETAILS: Record<SocialSetting, string> = {
  // Built Environment
  [SocialSetting.Urban]: 'A bustling urban environment.',
  [SocialSetting.Rural]: 'A countryside or agricultural setting.',
  [SocialSetting.Coastal]: 'A setting defined by its proximity to the sea.',
  [SocialSetting.Mountainous]: 'A setting defined by high elevation and rugged terrain.',
  [SocialSetting.Industrial]: 'A space of manufacturing or production.',
  [SocialSetting.Domestic]: 'A private home or living space.',
  [SocialSetting.Suburban]: 'A quiet, residential area.',
  [SocialSetting.Exurban]: 'A setting beyond the suburbs, often semi-rural.',
  [SocialSetting.SmallTown]: 'A small town with complex social dynamics.',
  [SocialSetting.PortCity]: 'A city defined by its maritime trade and connection.',
  [SocialSetting.UniversityTown]: 'A town centered around an academic institution.',
  [SocialSetting.PostIndustrialTown]: 'A town struggling with the decline of its manufacturing base.',
  [SocialSetting.HighRiseEstate]: 'A dense residential area defined by high-rise buildings.',
  [SocialSetting.InformalSettlement]: 'A community built without formal planning or infrastructure.',
  [SocialSetting.WarehouseDistrict]: 'An area characterized by large storage and industrial buildings.',
  [SocialSetting.HospitalCareSector]: 'A setting defined by the presence of medical and care facilities.',
  [SocialSetting.SchoolCampus]: 'A space for education and academic life.',
  [SocialSetting.PrisonCarceralEdge]: 'A space defined by the presence of carceral institutions.',
  [SocialSetting.FarmBelt]: 'An area defined by large-scale agricultural production.',
  [SocialSetting.IslandCommunity]: 'A secluded settlement on an island.',
  [SocialSetting.OffshoreMaritimeEconomy]: 'A setting defined by maritime and offshore industries.',
  // Economic Condition
  [SocialSetting.PrecariousServiceEconomy]: 'A space defined by precarious, on-demand labor.',
  [SocialSetting.PrecariousHousing]: 'A setting defined by the instability of modern rental/ownership markets.',
  [SocialSetting.GentrifiedFringe]: 'A neighborhood in the process of rapid social and economic transformation.',
  [SocialSetting.DebtSociety]: 'An environment defined by widespread financial instability.',
  [SocialSetting.AusterityLandscape]: 'A setting shaped by reduced public spending and economic hardship.',
  [SocialSetting.PlatformLabourZone]: 'A space defined by the influence of platform-based work.',
  [SocialSetting.SpeculativePropertyMarket]: 'An environment driven by real estate speculation.',
  [SocialSetting.DecliningMainStreet]: 'A traditional commercial area in economic decline.',
  [SocialSetting.LuxuryRedevelopmentZone]: 'An area transformed by high-end development.',
  [SocialSetting.CoLivingSharedRental]: 'A setting defined by shared, often unstable, living arrangements.',
  [SocialSetting.HomelessnessInterface]: 'A space where the reality of homelessness is most visible.',
  [SocialSetting.StartupEcosystem]: 'An environment driven by innovation and rapid growth.',
  [SocialSetting.CreativePrecarityCluster]: 'A setting defined by the precarious nature of creative work.',
  [SocialSetting.InfluencerEconomy]: 'An environment driven by the influence of digital creators.',
  [SocialSetting.CareEconomy]: 'A setting defined by the labor of care and support.',
  [SocialSetting.MigrantLabourSystem]: 'An environment defined by the presence and labor of migrant workers.',
  [SocialSetting.ShadowEconomy]: 'A space defined by informal and often illegal economic activity.',
  // Institutional Context
  [SocialSetting.CorporateCampus]: 'A setting that blurs the lines between work, life, and surveillance.',
  [SocialSetting.NGOHumanitarianSpace]: 'A space defined by the presence of humanitarian organizations.',
  [SocialSetting.CompanyTown]: 'A town dominated by a single employer.',
  // Political Regime
  [SocialSetting.SurveillanceState]: 'An environment where observation is constant and inescapable.',
  [SocialSetting.BorderRegime]: 'A setting defined by the enforcement of borders.',
  [SocialSetting.OccupiedMilitarisedZone]: 'A space defined by military presence and occupation.',
  [SocialSetting.BiosecurityState]: 'An environment defined by the management of biological risks.',
  [SocialSetting.PrivatisedPublicRealm]: 'A public space that has been privatized and restricted.',
  [SocialSetting.EcologicalCollapseFrontier]: 'A setting defined by the immediate impact of ecological collapse.',
  [SocialSetting.DisasterRecoveryZone]: 'A space defined by the ongoing process of disaster recovery.',
  [SocialSetting.AutomatedCity]: 'An environment defined by high levels of automation.',
  [SocialSetting.ClimateRefugeeCamp]: 'A setting defined by the displacement caused by ecological collapse.',
  // Digital
  [SocialSetting.PlatformPublicSphere]: 'A virtual space where social, political, or economic exchange occurs.',
  [SocialSetting.OnlineCommons]: 'A digital space for shared resources and community.',
  [SocialSetting.NetworkedPublic]: 'A public space defined by its digital connectivity.',
};

export const ATMOSPHERE_MODE_DETAILS: Record<string, string> = {
  'Rain': 'Atmosphere defined by precipitation.',
  'Fog': 'Atmosphere defined by obscurity and mystery.',
  'Night': 'Atmosphere defined by darkness and secrecy.',
  'Tense': 'Atmosphere defined by suspense and anxiety.',
  'Oppressive': 'Atmosphere defined by a heavy, stifling feeling.',
  'Cold': 'Atmosphere defined by low temperatures and detachment.',
  'Chaotic': 'Atmosphere defined by disorder and unpredictability.',
  'Clear': 'Atmosphere defined by visibility and starkness.',
  'Wind': 'Atmosphere defined by movement and turbulence.',
  'Storm': 'Atmosphere defined by elemental violence.',
  'Drought': 'Atmosphere defined by scarcity and heat.',
  'Industrial': 'Atmosphere defined by machinery and artificiality.',
  'Claustrophobic': 'Atmosphere defined by a lack of space.',
  'Expansive / Desolate': 'Atmosphere defined by vast, empty spaces.',
  'Techno-Melancholic': 'Atmosphere defined by digital sadness.',
  'Fever-Dream': 'Atmosphere defined by surreal intensity.',
  'Quietly Menacing': 'Atmosphere defined by subtle, underlying threat.',
  'Ethereal': 'Atmosphere defined by lightness and unreality.',
  'Nostalgic': 'Atmosphere defined by longing for the past.',
  'Surreal': 'Atmosphere defined by the uncanny.',
  'Vibrant': 'Atmosphere defined by energy and color.',
  'Melancholic': 'Atmosphere defined by sadness and reflection.',
  'Cuskian Detachment': 'Atmosphere defined by analytical distance.',
  'Stroutian Intimacy': 'Atmosphere defined by quiet, personal connection.',
  'Wardian Visceral': 'Atmosphere defined by raw, haunting intensity.',
  'Algorithmic Dissonance': 'The feeling of being out of sync with the digital systems that govern daily life.',
  'Bureaucratic Cold': 'The dehumanizing, emotionless atmosphere of large-scale institutions.',
  'Precarious': 'A tone defined by the constant, low-level anxiety of instability.',
  'Hyper-Connected / Isolated': 'The paradox of being constantly connected digitally while feeling profoundly isolated physically.',
  'Surveillance Paranoia': 'A tone defined by the feeling of being constantly watched or recorded.',
  'Eco-Anxious': 'A tone defined by the looming, existential dread of ecological collapse.',
};

export const THEMATIC_FOCUS_DETAILS: Record<string, string> = {
  'Class & Power': 'Exploration of social hierarchy and influence.',
  'Intimacy & Connection': 'Exploration of human relationships.',
  'Technology & Modern Life': 'Exploration of the impact of technology.',
  'Gentrification & Place': 'Exploration of urban transformation.',
  'Identity & Self': 'Exploration of personal and social identity.',
  'Memory & The Past': 'Exploration of how the past shapes the present.',
  'Desire & Longing': 'Exploration of human wants and needs.',
  'Social Change': 'Exploration of societal evolution.',
  'Family Dynamics': 'Exploration of family relationships.',
  'Art & Culture': 'Exploration of creative and cultural expression.',
  'Ecological Grief': 'Exploration of loss related to the environment.',
  'Digital Hauntology': 'Exploration of the ghosts of the digital age.',
  'Bureaucratic Absurdity': 'Exploration of the irrationality of systems.',
  'Intergenerational Trauma': 'Exploration of inherited pain.',
  'Urban Decay / Renewal': 'Exploration of the cycle of urban change.',
  'Algorithmic Bias': 'The hidden, systemic prejudices embedded in digital systems.',
  'Precarity': 'The condition of economic and social instability.',
  'Surveillance Capitalism': 'The economic system based on the commodification of personal data.',
  'Climate Justice': 'The intersection of ecological collapse and social inequality.',
  'Digital Alienation': 'The feeling of estrangement caused by digital mediation.',
  'Institutional Failure': 'The collapse of trust in the systems that govern society.',
  'Performative Activism': 'The critique of social action that is more about image than substance.',
};

export const SENTENCE_CADENCE_DETAILS: Record<SentenceCadence, string> = {
  [SentenceCadence.Staccato]: "Short, urgent, percussive sentences. Minimalist and high-impact.",
  [SentenceCadence.Standard]: "A balanced mix of sentence lengths and structures.",
  [SentenceCadence.Ciceronian]: "Long, winding, clause-heavy sentences. Digressive and flowing.",
};

export const REVISION_FOCUS_DETAILS: Record<RevisionFocus, string> = {
  [RevisionFocus.EnhanceEcology]: "Focus on specific forensic details, procedural accuracy, and investigative logic.",
  [RevisionFocus.DeepenAtmosphere]: "Increase the atmospheric pressure, focus on mood, light, and tension.",
  [RevisionFocus.FixRhythm]: "Improve the musicality and flow of the prose.",
  [RevisionFocus.MythicLayering]: "Add layers of historical context, social commentary, or thematic resonance.",
  [RevisionFocus.StripBack]: "Remove adjectives and adverbs, focusing on nouns and verbs for a bleak, minimalist feel.",
  [RevisionFocus.EtymologicalRewilding]: "Replace common words with their historical or specialized equivalents.",
  [RevisionFocus.ClicheHunter]: "Identify and replace standard crime-writing tropes with original imagery.",
  [RevisionFocus.Marginalia]: "Apply a specific editorial note to a selected section of text.",
};
